### ISSUE TITLE
Implement image tags

### ISSUE THREAD

**Issue by oferkv** [oferkv/phototonic#17]

**Comment by oferkv** [comment]
Done.

**Comment by fguzm** [comment]
How do I add new tags to an image? Cannot find such a fuction.

**Comment by oferkv** [comment]
Hey fguzm!
When you select an image or multiple images, you can create a new tag and assign it to them using the new tags dock, like in this screenshot for example:
![tags_example](https://cloud.githubusercontent.com/assets/4776676/8397422/4ed5b850-1dd3-11e5-9bac-426126c56f92.jpg)

**Comment by howudodat** [comment]
just curious why you chose IPTC instead of XMP tags?  Any chance on an option to write to either?  Also is there a way to edit other IPTC fields or only "keywords"?

**Comment by oferkv** [comment]
Hey.
I think I was inspired by how gThumb's implementation.
But does it matter what keywords are used?
Editing image metadata would be a nice feature...

**Comment by howudodat** [comment]
I have found that it doesn't matter too much whether to use IPTC or XMP, unless one is a Photoshop fanatic :).  It would be nice however to edit other IPTC metadata (title, caption, etc)

**Comment by oferkv** [comment]
Opened issue for this: Allow editing metadata (Exif fields...). #207
