### ISSUE TITLE
Allow click on X to close image without closing Phototonic

### ISSUE THREAD

**Issue by barjac** [oferkv/phototonic#172]
I often browse though photos using only the mouse with the keyboard out of reach.
I can scroll though folders using the scroll wheel but I can only only close the image with the right click context menu which is rather frustrating.
My natural instinct is to close the image with the X - which instantly closes Phototonic.
Could the X be changed to close just the image and drop to the parent window with the thumbnails view, where another click on X could then close the application?

**Comment by oferkv** [comment]
Hi Barjac; 
Double click (or middle click when using reverse mouse option) also closes the image, isn't that a preferred option? pressing X to close is a bit confusing behavior... seems kinda hackish.

**Comment by barjac** [comment]
Thanks oferkv - yes that will do fine! I never thought to DOUBLE click the image - I always set up KDE file managers etc. for single click actions, so double click is a bit unusual for me.
Closing then :)
