### ISSUE TITLE
moving image "up" does not work

### ISSUE THREAD

**Issue by dbluelle** [oferkv/phototonic#173]
If I have an image zoomed beyond the size of the screen, I can move around in the image with the down, left and right keys, but up doesn't do anything.
What's strange is that in the default settings the "Nach oben" key is set to "alt+up", 
but alt+up also doesn't work.
The other keys "Nach unten", "Nach links" und "Nach rechts" are correctly set to "down","left" and "right".
Moving with the cursor keys inside the list view works as expected.

**Comment by krzyc** [comment]
It is bug related to German translation - two phrases, which define keys, are translated to "nach oben", which confuses Phototonic. In English one is "up", and other is "move up".

I can not tell whether German translation is correct, but even if it is correct, I propose to change both sources of problem:
1. change "up" phrase, which for me is unclear, to "Go up" (as in KDE) or even "Parent Directory" (as in Qt Creator),
2. change way Phototonic saves key bindings to language neutral (to exclude same bugs in future and allow language switching feature, which will break key bindings after every language change).

**Comment by krzyc** [comment]
Oferkv, bug is probably fixed now, but what do you think about replacing "up" phrase with something more descriptive? I have proposed "Go up" (as in KDE) or "Parent Directory" (as in Qt Creator). Or maybe you have another proposition?

**Comment by oferkv** [comment]
Yes, your proposition sounds good. It can be a bit funny that the "Go" menu will say Go->go up, but its no big deal.
