### ISSUE TITLE
Directory navigation anomolies

### ISSUE THREAD

**Issue by barjac** [oferkv/phototonic#179]
When browsing the file structure from within phototonic the there is a strange issue.
Directories are shown with a triangle to expand them when they have further sub-directories, however many (but not all) that do not have sub directories still show the expansion triangles which rotate when clicked, but otherwise do nothing.
Not all directories without sub-dirs have the triangles, but as yet I can see no reasoning behind why some that should not, do and some correctly don't :\
http://mtf.no-ip.co.uk/pub/linux/barjac/tests/phototonic_dir.png

**Comment by barjac** [comment]
This is in Phototonic v1.5.32 - I don't recall seeing this previously but I may have just not noticed it.

**Comment by barjac** [comment]
Hmm - what happened to git describe?
[baz@jackodesktop phototonic]$ git describe
v1.5.48-4-g6a5608a
...should that not be v1.5-48-g6a5608a? - I'm confused :\

**Comment by oferkv** [comment]
Oh... My mistake, I added  a tag that causes this, will fix ASAP.

**Comment by oferkv** [comment]
OK fixed.

**Comment by barjac** [comment]
Thanks - my script is now creating phototonic-1.5.54.tar.gz
...and I can confirm that the expansion marks are now working correctly :)
