### ISSUE TITLE
Open multiple files?

### ISSUE THREAD

**Issue by michael-heerdegen** [oferkv/phototonic#183]
Hello,

when I try to open phototonic with a set of given files from the command line:

```
phototonic file1.jpg file2.jpg
```

it says:

```
Usage: phototonic [FILE or DIRECTORY]...
```

But that's exactly what I'm trying to do.  I don't want to open separate instances of phototonic of course.

No problem if this doesn't fit the philosophy of the program (though I think it would be a useful feature), but in that case the usage message is quite confusing, or i don't understand it.

Thanks, Michael.

**Comment by barjac** [comment]
It does say FILE not FILES and specifying a single file does work correctly, as does specifying a directory.
Perhaps multiple file support could be a future enhancement.
Maybe you could put the required files into a directory for your purpose?

**Comment by oferkv** [comment]
Yes, if not multiple instances will open, then this behavior seems to be related to the "image lists" feature request (loading multiple images in to the thumbnail view).

**Comment by michael-heerdegen** [comment]
barjac <notifications@github.com> writes:

> It does say FILE not FILES and specifying a single file does work
> correctly, as does specifying a directory.

Actually it says "Usage: phototonic [FILE or DIRECTORY]...".  If the
ellipsis doesn't mean "more files and directories", then I'm even more
confused about what the ellipsis stands for.  I guess it could be made
clearer in any case.

**Comment by barjac** [comment]
Ah indeed, I missed the ellipsis.

**Comment by oferkv** [comment]
Fixed.

**Comment by michael-heerdegen** [comment]
oferkv <notifications@github.com> writes:

> Fixed.

Hey - thanks!
