### ISSUE TITLE
dock resize gets into unusable state

### ISSUE THREAD

**Issue by barjac** [oferkv/phototonic#188]
Not sure just how this happened but with the config in the paste below, it's impossible to widen the left pane to see the file system correctly.
After launch the move cursor tool appears when placed on the divider, but on clicking it to drag it closes and does nothing. Then it never re-appears. A new config fixes it.
It should not be possible to get into this situation from the GUI.
v1.5.54
https://paste.kde.org/pjnqnwvrj

**Comment by krzyc** [comment]
I can not reproduce it on current build on Kubuntu system. After changing config to yours I can still resize file system panel.

**Comment by oferkv** [comment]
Hi barjac, please check if it reproduces with the latest version, thanks!

**Comment by oferkv** [comment]
Please reopen if reproduces with latest ver, thanks!

**Comment by barjac** [comment]
No change unfortunately.
This is in Mageia 5 (which has just been released) and testing a new rpm build of Phototonic v1.6.4.

**Comment by oferkv** [comment]
Strange. Anyway, can you reproduce the corruption itself? Because the code that made it happen is now probably completely changed.
Note that there already is a 1.6.5 :)

**Comment by barjac** [comment]
I just re-tested this (new rpm) in a clean VM install of Mageia 5 and the problem is not there. I'm wondering if it may be a theme issue or some KDE settings problem.
I will test with a new user back on the real system.

**Comment by barjac** [comment]
OK I found the cause. \o/
A new user did not have the issue, but changing 
systemsettings->input devices->mouse->check "single click to open files and folders"
rather than the double click default reproduces the problem.
I always use the single click option :\

**Comment by oferkv** [comment]
Just tested this on KDE, switched between the modes and restarted many times, no issues occurred.

**Comment by barjac** [comment]
I went back to the VM and could not remove the problem by changing the system setting, so I renamed the conf and it worked again.
Here is a diff of the conf files the one with x suffix is the broken one.
https://paste.kde.org/pus9q43dv

**Comment by oferkv** [comment]
So as I understand those are the reproduction steps:
1. New user
2. Start Phototonic, all is good.
3. Change to single click
4. Open Phototonic and then close --> problem?

**Comment by barjac** [comment]
I just tried to reproduce again in the VM and I cannot, however going back to the broken .conf it is still broken.
https://paste.kde.org/pq47vdud8
