### ISSUE TITLE
Scroll bar in the tree view is buggy

### ISSUE THREAD

**Issue by do-i** [oferkv/phototonic#191]
I am using v1.5.54 on Crunchbang 11 and Crunchbang Plus Plus. When I use mouse wheel to scroll down in the file tree view, scroll goes up and down.
I noticed the same behavior in the image viewer. i.e., go next image by wheel down but it goes up and down.

This happens also in the thumbnail page scroll.

**Comment by pmattern** [comment]
FWIW can't confirm this running latest Git code on Arch Linux i686 or x86_64.

**Comment by do-i** [comment]
Peter,
Thanks for looking into this. I will try out the latest version.

**Comment by do-i** [comment]
I installed v1.6.2 on Crunchbang Plus Plus which runs on Virtualbox 4.3.30 which runs on Crunchbang 11. It is a lot better than v1.5.54. But, I still see the mouse wheel scrolling issue.
It happens about once in every 10 scroll. Each small scroll moves one row in thumbnail view.
Once in every 10 rows, rows stays or moves backwards.  
It's subtle but noticeable and annoying.

**Comment by oferkv** [comment]
Hi do-i!
Can you please provide detailed step by step instructions on how to reproduce this?
Thanks.

**Comment by sandsmark** [comment]
I'm not entirely sure what was the source of this bug, but I'm fairly sure this should fix it anyways: https://github.com/oferkv/phototonic/commit/55681a42029c6df8542240da541fad778fae5e5c

Feel free to reopen if you still can reproduce the issue with current git master.
