### ISSUE TITLE
Maximum zoom is very low

### ISSUE THREAD

**Issue by 0ion9** [oferkv/phototonic#199]
Just updated to latest git and spotted this, probably an easy fix:

Zoom only goes up to 350%. For small images, this is not adequate to properly view them; and the 'fit to display' option is not a practical alternative as it turns them into a huge blur.. Here is an example image at maximum zoom:
![screenshot_538](https://cloud.githubusercontent.com/assets/115782/10299560/f149ae7c-6c32-11e5-9f6d-01f99c60bd88.png)
(I included most of the side panel so that the text '14x12' would be visible, and also to give a sense of relative scale for the image display)

I would suggest 800%; it allows graphics as small as 8x8 to be displayed legibly.

**Comment by oferkv** [comment]
Fixed, please test. Thanks.
