### ISSUE TITLE
Support standard cmdline options for requesting help

### ISSUE THREAD

**Issue by 0ion9** [oferkv/phototonic#200]
I have just checked, neither of 

* `phototonic --help`
* `phototonic -h`

produce a help message; instead they complain that the directory '[current directory]/--help' (or similar) was not found.

Since there is also no man page or other documentation included in the package, it seems to me that the average CLI user would be justifiably lost when trying to find out whether phototonic has any commandline options.

The items I listed are standard ways of requesting help that work with most programs. 

Since I've looked at the source, I know that the usage message is printed only when more than one argument is given to phototonic.  It makes sense to print it then, of course, but it seems reasonable to also support the standard ways of asking for help.

**Comment by oferkv** [comment]
Fixed, please test, thanks.

**Comment by 0ion9** [comment]
@oferkv:

Looks good. `-h, --help` work as expected, `-l de` as expected, invalid option flags like '-foo' or '--foo' trigger usage message.
The only remaining way I can spot in which phototonic does not behave in a standard way is handling of `--`, which is generally used to ensure that filenames beginning with `-` are not interpreted as options. For example `phototonic -- -foo.png` (assuming that `-foo.png` is an existing file), should open -foo.png. However, this is typically a situation that can be worked around by prepending `./`, for example, so that the first character of the path is then `.` rather than `-`.

**Comment by oferkv** [comment]
Interesting, I will check that -file.jpg can at least be opened with the file manager.
Thanks!
