### ISSUE TITLE
can't set background color

### ISSUE THREAD

**Issue by deathtrip** [oferkv/phototonic#202]
My image background color is always ths same as Qt's default window border color - grey. Changing settings doesn't affect it.
I'm using version 1.7.1 ,Qt 5.5.1 on Arch Linux.

**Comment by oferkv** [comment]
Strange, can not reproduce, what DE are you using?

**Comment by deathtrip** [comment]
I use KDE 5.4.3, additionally when i save a custom color, it's gone after i restart the program.

**Comment by oferkv** [comment]
Fixed, please test.
