### ISSUE TITLE
External application could not be opened

### ISSUE THREAD

**Issue by HinzundKunz** [oferkv/phototonic#208]
When adding an external application, I always get the above error, no matter what I do or how I go about it.

**Comment by oferkv** [comment]
Hi;
What Distribution and DE are you using?
Thanks,
Ofer

**Comment by HinzundKunz** [comment]
Kubuntu 15.10, with launchpad backports enabled, KDE 5.5.3, Qt 5.5.1

**Comment by HinzundKunz** [comment]
Sorry, I always press the wrong button...

**Comment by oferkv** [comment]
What version of Phototonic are you using?

**Comment by HinzundKunz** [comment]
Phototonic v1.5.54

**Comment by oferkv** [comment]
Please check if this reproduces on latest version 1.7.19.

**Comment by HinzundKunz** [comment]
How do I do this? I'm not a programmer... I have used cmake and kdevelop to compile and install stuff, but nothing more...

**Comment by HinzundKunz** [comment]
Found it on the website... will give it a try.

**Comment by oferkv** [comment]
I see. Well this bug was probably solved some time ago, you can try running the latest version from GIT without messing up your system:
1. Download this: https://github.com/oferkv/phototonic/archive/master.tar.gz
2. Unzip+tar
3. qmake
4. make
5. Run locally ./phototonic

**Comment by HinzundKunz** [comment]
Well, it still doesn't work here... What exactly am I supposed to put in the "manage external application" dialogs? Maybe I'm doing something wrong...

**Comment by HinzundKunz** [comment]
I use phototonic to view a collection of svg files and would like to be able to open them in inkscape.

**Comment by oferkv** [comment]
You should pick the Inkscape executable as the target.

**Comment by HinzundKunz** [comment]
No - doesn't work... no errors at the command prompt either...

**Comment by oferkv** [comment]
Fixed in an older version, closing.
