### ISSUE TITLE
Delete to Trash

### ISSUE THREAD

**Issue by tomchezhl** [oferkv/phototonic#211]
Wish : Delete to Trash
If it is too complicated to delete to the Desktop Trash than perhaps to it's own Trash like Geeqie do.

**Comment by oferkv** [comment]
@FreeSlave what do you think about not having confirmation for move to trash at all?
In other words:
Move to trash -> no confirmation
Delete -> confirmation (depending on the "confirm delete" preference, same behavior as now).

**Comment by FreeSlave** [comment]
How about making it optional like in Dolphin? Look at Dolphin Preferences -> General -> Confirmations. It has confirmation settings for both trashing and deleting. By default moving to trash can be done without confirmation though.
Another thing that bothers me is keyboard shortcuts. We probably should go for Del as Move to trash and Shift+Del as Delete. Other applications follow the same rules. 
There's a little problem with delete operation in other places (like deleting bookmarks) - if we make real Delete as Shift+Del it would affect deleting bookmarks, i.e. user will not be able to use usual Del shortcut to delete a bookmark. We can make Move to trash action work with bookmarks too, though it does not make much sense as there will be no difference between two operations on bookmarks.

**Comment by oferkv** [comment]
Having separate "confirm" preferences for delete and trash can be great.
Delete key for trash and Shift+Delete key for Delete should be good.
I don't see an issue with the shortcuts as long as the concept is that Delete key action is "Delete" (move to trash), and Shift+Delete key action is "Delete Permanently". In other words: delete is always delete. Delete permanently is the exception that has a separate action key.

**Comment by oferkv** [comment]
Added the shortcut keys, and made by default Del move to trash, and Shift+Del Delete.
