### ISSUE TITLE
Using also Link for "open with external App"

### ISSUE THREAD

**Issue by tomchezhl** [oferkv/phototonic#212]
Wish : Using also Link for "open with external App"

I have installed Wine32 and Wine64 and Q4Wine on Debian8_64. For opening a 32bit_Win_App there is a working link from the linux desktop "env WINEPREFIX="/home/tom/.local/share/wineprefixes/wine32" wine C:\\Program\ Files\\XnView\\xnview.exe ". I like to use it also for "open with external App" in Phototonic.

**Comment by oferkv** [comment]
Hi, can you create a shell script that will open the image with that link?

**Comment by tomchezhl** [comment]
Hi, thanks for these info. It is a good idea. I'll try it and will
report the result to you.



Am 29.02.2016 um 21:05 schrieb oferkv:

**Comment by tomchezhl** [comment]
Hi, with the help of a shell script it is possible to open windows program in wine32, but it is not possible to take over a parameter. On the way are 3 programs involved (q4wine, wine32 and xnview). Only wine accepts an additional parameter.
```
#! /bin/sh
exec sh -c 'env WINEPREFIX="/home/tomh/.local/share/wineprefixes/wine32" wine C:\\Program\ Files\\XnView\\xnview.exe'
```
```
