### ISSUE TITLE
Translation into Portuguese of Brazil.

### ISSUE THREAD

**Issue by mnwstl** [oferkv/phototonic#216]
Hello! I would like to translate into Portuguese of Brazil (pt_BR). Is there any specific softwere for this or we use the text editor? Thank you!

**Comment by oferkv** [comment]
Hi, this should be helpful: http://doc.qt.io/qt-5/qtlinguist-index.html
Thanks!

**Comment by mnwstl** [comment]
Hi,
I sent the files to your email.
Marcos

**Comment by oferkv** [comment]
Added, thanks.

**Comment by mnwstl** [comment]
Thanks!

**Comment by oferkv** [comment]
Added credit, sorry for late reply.
