### ISSUE TITLE
please exchange preview and exif info

### ISSUE THREAD

**Issue by pauweh** [oferkv/phototonic#217]
I am more than confused about placing the image preview to the right and the exif infos below the files tree. The exif info are long and small. So all other tools allow to place tehm to the right.
All, ok only 99.5% of monitors for viewing photos are landscape 4x3, 9x6 or 3x2. That because 100% of photos do have a ratio something like this.
Did you ever think about this when placing landscape previews to a small portait portion of the monitor? Wasting a lot of space for simple blakc background?
And placing a small portrait style list like a table of exif words and numbers on a landscape portion of the screen below the folder tree?

**Comment by oferkv** [comment]
This can all be rearranged, so you mean that it's not reasonable only as the defaults? In that case it makes sense...

**Comment by oferkv** [comment]
Docks can be re-arranged as needed.
