### ISSUE TITLE
Is it allowed to use c++11 features in this project?

### ISSUE THREAD

**Issue by FreeSlave** [oferkv/phototonic#225]
I see `CONFIG += c++11` in project file, but could not find any actual usage of c++11 features in source code, so I have to ask.

**Comment by oferkv** [comment]
Added this to fix a build issue, but sure no problem using c++11 features.

**Comment by FreeSlave** [comment]
Ok, but do I need to stick to c++98 in PRs?

**Comment by FreeSlave** [comment]
@oferkv why did you assign me to it? It's not an issue, just a question.
I also misunderstood you answer then. So it's ok to use C++11, got it.
