### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by FreeSlave** [oferkv/phototonic#230]
I don't see any Windows support in project file (I mean regarding linking to exiv2 on Windows). Are you interested in supporting the Windows version at all?

**Comment by oferkv** [comment]
Not really. I mean, I wouldn't bother with it, but I wouldn't mind having it as long as it's is not intrusive.

**Comment by sandsmark** [comment]
master has explicit `win32` stuff to use mingw etc., so closing this.
