### ISSUE TITLE
Setting selected image as window icon should be optional

### ISSUE THREAD

**Issue by FreeSlave** [oferkv/phototonic#234]
I'm not sure why did you add this feature in the first place, but this may make it hard to find the phototonic in the taskbar, because it does not have a constant icon.
Also the size of produced icon is too small and it may look ugly if the desktop shows big icons in the taskbar.

**Comment by oferkv** [comment]
Actually it was added for making Phototonic easy to find on the panel. When you have a few windows open, it allows finding the one you need fast. This is similar to the same feature in Gimp.
Making it optional is a good idea.
I think the size doesn't really matter, it's not intended to be high quality, but I think I will improve the quality just a bit, Gimp seems to handle it OK.
