### ISSUE TITLE
[feature-request]Thumbnail preview in the lower left corner.

### ISSUE THREAD

**Issue by Cybermaxrus** [oferkv/phototonic#236]
I'm used to that miniature in the lower left corner, under the tree of the files. Is it possible to do so?
https://cdn4.geckoandfly.com/wp-content/uploads/2014/03/fast-stone-image-viewer-acd-see-free-acdsee.jpg

**Comment by oferkv** [comment]
Sure, you can move it around and place it in any window corner (unhide the dock title bars to do so, if they are hidden).
