### ISSUE TITLE
Portuguese translation didn't work.

### ISSUE THREAD

**Issue by mnwstl** [oferkv/phototonic#239]
Hello! I installed the new version, but the translation to the Portuguese did not work. I checked that there are the files phototonic_pt.QM and PHOTOTONIC_PT.TS, but the program was in English.

**Comment by FreeSlave** [comment]
In Phototonic translations are taken from resources, not external files, and phototonic_pt.qm is not included in resources.

**Comment by mnwstl** [comment]
I downloaded the files and in the folder "Phototonic-master/Translations/" There are the files mentioned. When I compiled and installed and the files were not recognized.

**Comment by FreeSlave** [comment]
@mnwstl does it work for you on the latest master?

**Comment by oferkv** [comment]
For me it does BTW, but I'm testing like this: ./phototonic -l pt

**Comment by FreeSlave** [comment]
Yeah, but I mean for Portugal locale. For me it works if I start with LANGUAGE=pt_PT environment variable.

**Comment by mnwstl** [comment]
OK! It looks good!
