### ISSUE TITLE
could not find the function "find duplicate image"

### ISSUE THREAD

**Issue by zerobikappa** [oferkv/phototonic#247]
I could not find "find duplicate image" after I updated photonic, may I know if it still has this function in new version?

**Comment by oferkv** [comment]
Hi, the old find dupes feature was very basic hash matching.
Instead now that there is file list support, you can use tools like findimagedupes, which even finds duplicates by content similarities.
For example:
findimagedupes  -p /usr/bin/phototonic -R ~/Desktop/Pictures/
