### ISSUE TITLE
Unable to open image with wrong suffix

### ISSUE THREAD

**Issue by wAmpIre** [oferkv/phototonic#253]
Photonic marks images as "Unable to read image data" if the suffix of the filename is wrong. For example error message on command line when PNG image saved as .jp(e)g:
```
Not a JPEG file: starts with 0x89 0x50
libpng warning: iCCP: known incorrect sRGB profile
```

It should not depend on the suffix but do a magic byte lookup like "*file*".

**Comment by sandsmark** [comment]
With current master works with wrong file endings, can you test again?

**Comment by sandsmark** [comment]
It works here (and I don't see how it can't), so please re-open if it doesn't for you.
