### ISSUE TITLE
ImageViewer.h:23:10: fatal error: exiv2/exiv2.hpp: No such file or directory

### ISSUE THREAD

**Issue by Cybermaxrus** [oferkv/phototonic#255]
When I write the command "make" in the terminal, I get the message:
> g++ -c -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I. -isystem /usr/local/include -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o main.o main.cpp
> In file included from Phototonic.h:23,
>                  from main.cpp:19:
> ImageViewer.h:23:10: fatal error: exiv2/exiv2.hpp: No such file or directory
>  #include <exiv2/exiv2.hpp>
>           ^~~~~~~~~~~~~~~~~
> compilation terminated.
> make: *** [Makefile:821: main.o] Error 1
> 
I checked in the synaptic package manager that exiv2 version 0.25-4 is installed.
Debian GNU/Linux 10 (buster)

**Comment by amgadelsaiegh** [comment]
same here on linux mint 19

**Comment by oferkv** [comment]
This should work if the dev package is installed (libexiv2-dev).

**Comment by sandsmark** [comment]
You need to install libexiv2-dev as oferkv said:

https://packages.debian.org/search?searchon=contents&keywords=exiv2.hpp&mode=path&suite=stable&arch=any
