### ISSUE TITLE
Please list the supported image formats explicitly

### ISSUE THREAD

**Issue by dandv** [oferkv/phototonic#259]
The README says "common image formats". Can it be clearer?

Does it support WEBP? HEIC? etc.

**Comment by okashayov** [comment]
Hi;
The formats supported by default are listed here: https://doc.qt.io/qt-5/qimage.html#reading-and-writing-image-files
Some additional formats could be supported, SVG for example if the libqt5svg5 module is installed.
Formats could be listed in help using QImageWriter::supportedImageFormats().
